spring:
  application:
    name: cicdtest3

  datasource:
    url: ${MY_DATA_SOURCE}  # ?? ??? URL? ??
    username: ${MY_DATA_USERNAME}  # ?? ??? ???? ??
    password: ${MY_DATA_PASSWORD}  # ?? ??? ???? ??
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL ???? ??


  jpa:
    hibernate:
      ddl-auto: update  # ?????? ??? ?? ???? (?? ???? ??)
      dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 8.x? Dialect ??
    show-sql: true  # ???? SQL ?? ??? ??
    format-sql: true  # SQL ?? ?? ? ??? ??
    use_sql_comments: true  # SQL ???? ??? ???? ?? ?? ??

logging:
  level:
    org.springframework.jdbc.datasource: DEBUG
    org.springframework.boot.jdbc: DEBUG


